# Spring Configuration
spring:
  application:
    name: wallet-creation-application
  main:
    web-application-type: reactive

# Server Configuration
server:
  port: 8080

# Logging Configuration
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    es.in2.wca: DEBUG

## Actuator Configuration
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, loggers, metrics, prometheus
      base-path: /
      path-mapping:
        health: health
        info: info
        loggers: loggers
        metrics: metrics
        prometheus: prometheus
  endpoint:
    health:
      enabled: true
      show-details: always
    loggers:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true

# Documentation Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: method

wallet-data:
  url: http://localhost:8086

wallet-wda:
  url: http://localhost:4200

wallet-crypto:
  url: http://localhost:8087

auth-server:
  domain: https://issuerkeycloak.demo.in2.es/realms/EAAProvider
  token-endpoint: https://issuerkeycloak.demo.in2.es/realms/EAAProvider/verifiable-credential/did:key:z6MkqmaCT2JqdUtLeKah7tEVfNXtDXtQyj4yxEgV11Y5CqUa/token

openapi:
  server:
    url:
    description:
  info:
    title:
    version:
    description:
    termsOfService:
    license:
      name:
      url:
    contact:
      email:
      name:
      url:
